dataset_root : dataset
artifacts_root : artifacts

data_ingestion : 
  dataset_path : dataset
  train_data_url : http://images.cocodataset.org/zips/train2017.zip
  validation_data_url : http://images.cocodataset.org/zips/val2017.zip
  data_anotations_url : http://images.cocodataset.org/annotations/annotations_trainval2017.zip

feature_extraction :
  train_data_path : dataset/train/train2017
  val_data_path : dataset/val/val2017
  features_path : artifacts

prepare_captions :
  train_annotations_path : dataset/annotations/annotations/captions_train2017.json
  param_path : params.yaml
  dest_path : artifacts

  