stages:
  data_ingestion : 
    cmd : python src/ImageCaptionGenerator/pipelines/stage_01_data_ingestion.py
    deps :
      - src/ImageCaptionGenerator/pipelines/stage_01_data_ingestion.py
    outs :
      - dataset/train
      - dataset/val
      - dataset/annotations
